I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'male.jpg'>:
  File "game/script.rpy", line 33, in script
    show male
IOError: Couldn't find file 'male.jpg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script
    show male
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 652, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/exports.py", line 1180, in say
    who(what, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/character.py", line 1016, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/character.py", line 817, in do_display
    **display_args)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/character.py", line 566, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 2635, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 3118, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 2041, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 485, in renpy.display.render.render_screen
  File "render.pyx", line 233, in renpy.display.render.render
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/layout.py", line 717, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "accelerator.pyx", line 108, in renpy.display.accelerator.transform_render
  File "render.pyx", line 233, in renpy.display.render.render
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/image.py", line 414, in render
    return wrap_render(self.target, width, height, st, at)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/image.py", line 229, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 145, in renpy.display.render.render
  File "render.pyx", line 233, in renpy.display.render.render
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/im.py", line 580, in render
    return cache.get(self, render=True)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/im.py", line 266, in get
    surf = image.load()
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/im.py", line 625, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/loader.py", line 555, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'male.jpg'.

Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
RenpyTest 1.0
Tue Apr 10 07:54:32 2018
